[package]
name = "mass-assignment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
lockfree = "0.5.1"
ndarray = { version = "0.15.6", features = ["rayon"] }
rand = "0.8.5"
